apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecociente-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecociente-api.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "ecociente-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "ecociente-api.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      containers:
        - name: {{ include "ecociente-api.fullname" . }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          {{- if or (and .Values.configMap.enabled .Values.configMap.data) .Values.secret.existingSecret }}
          envFrom:
            {{- if and .Values.configMap.enabled .Values.configMap.data }}
            - configMapRef:
                name: {{ include "ecociente-api.configMapName" . }}
            {{- end }}

            {{- if .Values.secret.existingSecret }}
            - secretRef:
                name: {{ .Values.secret.existingSecret }}
            {{- end }}
          {{- end }}

          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          {{- end }}

          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}

          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}