{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ecociente-api.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecociente-api.labels" . | nindent 4 }}

  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  {{- with .Values.ingress.tls }}
  {{- if and .enabled $.Values.ingress.host }}
  tls:
    - hosts:
        - {{ $.Values.ingress.host | quote }}
      secretName: {{ .secretName | quote }}
  {{- end }}
  {{- end }}

  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "ecociente-api.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
    {{- else }}
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "ecociente-api.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
{{- end }}
