apiVersion: v1
kind: Secret
metadata:
  name: autenticacao-secret
  namespace: ecociente
type: Opaque
stringData:
  DB_URL: "SUBSTITUA_PELA_URL_JDBC"
  DB_USER: "SUBSTITUA_PELO_USUARIO"
  DB_PASSWORD: "SUBSTITUA_PELA_SENHA"
  JWT_SECRET: "SUBSTITUA_PELO_SEGREDO_JWT"