replicaCount: 1

fullnameOverride: v26-infra-teste-api

image:
  repository: ecociente/ecociente
  tag: v26-infra-teste-1.0.0
  pullPolicy: IfNotPresent

containerPort: 8080

configMap:
  enabled: true
  nameOverride: v26-infra-teste-config
  data: {}

secret:
  existingSecret: ""

service:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: traefik
  host: ""
  path: /
  pathType: Prefix
  annotations: {}

  tls:
    enabled: false
    secretName: ""

probes:
  startup:
    enabled: true
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 30

  readiness:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

  liveness:
    enabled: true
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

podLabels: {}
